name:                sixty
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/ollef/sixty#readme
license:             BSD3
author:              Olle Fredriksson
maintainer:          fredriksson.olle@gmail.com
copyright:           2019 Olle Fredriksson
category:            Web
extra-source-files:
- README.md
data-files:
- builtin/Builtin.vix

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wtabs
  - -funbox-strict-fields

default-extensions:
  - NoImplicitPrelude

dependencies:
  - base >= 4.7 && < 5
  - prettyprinter
  - protolude
  - rock
  - unordered-containers

library:
  source-dirs: src
  dependencies:
    - aeson
    - aeson-casing
    - containers
    - data-default
    - dependent-map
    - dependent-sum
    - dependent-sum-template
    - directory
    - filepath
    - fingertree
    - haskell-lsp
    - lens
    - mtl
    - parsers
    - parsix
    - rope-utf16-splay
    - stm
    - text
    - transformers
    - vector

executables:
  sixty:
    source-dirs: app
    main: Main.hs
    dependencies:
      - optparse-applicative
      - sixty
      - text

tests:
  test-sixty:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - directory
      - filepath
      - sixty
      - tasty
      - tasty-hunit
      - text
