name:                sixty
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/ollef/sixty#readme
license:             BSD3
author:              Olle Fredriksson
maintainer:          fredriksson.olle@gmail.com
copyright:           2019 Olle Fredriksson
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - dependent-map
  - dependent-sum-template
  - fingertree
  - parsers
  - parsix
  - prettyprinter
  - protolude
  - rock
  - text
  - transformers
  - vector
  - unordered-containers

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wtabs
  - -funbox-strict-fields
  - -XNoImplicitPrelude

library:
  source-dirs: src

executables:
  sixty:
    source-dirs: app
    main: Main.hs
    dependencies:
      - sixty

tests:
  test-sixty:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - directory
      - filepath
      - sixty
      - tasty
      - tasty-hunit
      - unordered-containers
