resolver: lts-14.3
packages:
- .
extra-deps:
- parsix-0.2.1.0
- git: https://github.com/ollef/rock.git
  commit: 88705e6865118680f4ba0702f1d7685d90aef3e2
- git: https://github.com/fpco/ghc-prof-flamegraph.git
  commit: 8edd3b4806adeb25a4d55bed51c3afcc8e7a8e14
