resolver: lts-14.12
packages:
- .
extra-deps:
- parsix-0.2.1.0
- git: https://github.com/ollef/rock.git
  commit: 1c489a5599a232efbda6b142d2ee373e4d7ec391
- git: https://github.com/fpco/ghc-prof-flamegraph.git
  commit: 8edd3b4806adeb25a4d55bed51c3afcc8e7a8e14
